default: &mailer
  address: 'smtp.gmail.com'
  port: 587
  domain: 'gmail.com'
  user_name: 'user'
  password: 'passwd'
  authentication: 'plain'
  enable_starttls_auto: true

development:
  <<: *mailer

production:
  <<: *mailer
